spring:
  cache:
    type: redis
  mongodb:
    uri: mongodb://localhost:27017,localhost:27018,localhost:27019/product_catalog?replicaSet=rs0
  data:
    redis:
      host: localhost
      port: 6379
      password: algashop
      database: 0
      timeout: 600
  cloud:
    aws:
      region:
        static: us-east-1
      endpoint: http://algashop-localstack:4566 # em prod não precisa
      credentials:
        access-key: LSIAQAAAAAAVNCBMPNSG
        secret-key: test
      s3:
        enabled: true
        path-style-access-enabled: true # em prod não precisa, facilita o uso em local
  security: # apontamos o resource para authorization server para ter validação e busca de chave públicas
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://algashop-authorization-server:9000 # url de authorization server

logging:
  level:
    org.mongodb.driver.protocol.command: DEBUG
#    org.mongodb.driver.protocol.query: DEBUG
#    org.mongodb.driver.connection: DEBUG
    org.mongodb.driver.cluster: OFF

algashop:
  data-load:
    enabled: true
    auto-drop: true
    sources:
      - location: db/testdata/categories.json
        collection: categories
      - location: db/testdata/products.json
        collection: products
  mapping:
    image-storage-url: http://algashop-localstack:4566/algashop-product-image
  storage:
    s3:
      bucket-name: algashop-product-image

