# config.import traz os secrets e parameters da aws (LocalStack) para este arquivo env.
# O seed é feito pelo etc/aws/init.sh (parameters.csv / secrets.csv).

spring:
  config:
    import:
      - aws-secretsmanager:/secret/algashop/product-catalog/redis?prefix=catalog.secrets.redis.
      - aws-parameterstore:/config/algashop/product-catalog?prefix=catalog.params
      - aws-parameterstore:/config/algashop/shared?prefix=shared.params
  cache:
    type: redis
  mongodb:
    uri: ${catalog.params.mongodb.uri}
  data:
    redis:
      host: ${catalog.params.redis.host}
      port: ${catalog.params.redis.port}
      password: ${catalog.secrets.redis.password}
      database: ${catalog.params.redis.database}
      timeout: ${catalog.params.redis.timeout}
  cloud:
    aws:
      region:
        static: us-east-1
      endpoint: http://algashop-localstack:4566 # em prod não precisa
      credentials:
        access-key: LSIAQAAAAAAVNCBMPNSG
        secret-key: test
      s3:
        enabled: true
        path-style-access-enabled: true # em prod não precisa, facilita o uso em local
  security: # apontamos o resource para authorization server para ter validação e busca de chave públicas
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${shared.params.auth-server-url} # url de authorization server
  kafka:
    bootstrap-servers: algashop-kafka-1:9092,algashop-kafka-2:9093,algashop-kafka-3:9094
    #ponto inicial de conexão
    admin:
      fail-fast: true # Falha rápida caso não consiga se conectar ao cluster
      auto-create: true # Permite a criação automática de tópicos caso não existam
      modify-topic-configs: false # Impede a modificação de configurações de tópicos existentes
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer # chave String
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer # valor Json
      properties:
        spring.json.type.mapping: # customiza o type id do path completo com somente a referencia da classe
          ProductCatalog.ProductDelistedIntegrationEvent:com.algaworks.algashop.product.catalog.application.product.event.ProductDelistedIntegrationEvent,
          ProductCatalog.ProductListedIntegrationEvent:com.algaworks.algashop.product.catalog.application.product.event.ProductListedIntegrationEvent,
          ProductCatalog.ProductAddedIntegrationEvent:com.algaworks.algashop.product.catalog.application.product.event.ProductAddedIntegrationEvent

logging:
  level:
    org.mongodb.driver.protocol.command: DEBUG
#    org.mongodb.driver.protocol.query: DEBUG
#    org.mongodb.driver.connection: DEBUG
    org.mongodb.driver.cluster: OFF
    com.netflix.discovery.DiscoveryClient: OFF # desativa error eureka em dev
    com.netflix.discovery: OFF
    com.netflix.eureka: OFF

algashop:
  data-load:
    enabled: ${catalog.params.data-load.enabled}
    auto-drop: ${catalog.params.data-load.auto-drop}
    sources:
      - location: db/testdata/categories.json
        collection: categories
      - location: db/testdata/products.json
        collection: products
  mapping:
    image-storage-url: ${catalog.params.mapping.image-storage-url}
  storage:
    s3:
      bucket-name: ${catalog.params.storage.s3.bucket-name}
  messaging:
    kafka:
      product-event-topic-name: product-catalog.product.events

eureka:
  client:
    serviceUrl:
      defaultZone: ${shared.params.service-registry-url}/eureka
    healthcheck:
      enabled: true # habilita o health em eureka para status de serviço dentro de eureka
  instance:
    instanceId: ${random.uuid} # cada instancia replicada ganha um id unico
    prefer-ip-address: true # configura rede alcançável via docker
